import type { DesignTokens } from "@sitegen/shared-ui/types.ts";

// VITRINA design language: modern Russian retail storefront.
//
// Nine palettes in three families, so a portfolio of seller sites never reads as recolors:
//   0-1  TECH   — near-black rooms, one electric accent, mono numerals. Gadgets, tools, auto.
//   2-4  CRAFT  — warm paper, muted earth accents, an editorial serif. Home, textiles, food.
//   5-8  POP    — bright grounds, saturated candy accents, chunky geometric type. Beauty, kids, sport.
// Each palette also names its opposite room (--color-ink / --color-ink-text plus the accent that
// stays readable on it, --color-ink-primary): the surface the
// delivery and final-CTA blocks switch to, so every site has one hard visual break rather than
// scrolling as an undifferentiated wall of cards.
// Every family also owns its corner radius (tech = tight, craft = soft-square, pop = pill-round),
// so the shape language changes with the color, not just the hue.
//
// All families ship full Cyrillic coverage and are loaded by the template's Base layout;
// the system fallbacks cover the pre-font flash.
const UNBOUNDED = "'Unbounded', 'Trebuchet MS', system-ui, sans-serif";
const GOLOS = "'Golos Text', -apple-system, 'Segoe UI', system-ui, sans-serif";
const MANROPE = "'Manrope', -apple-system, 'Segoe UI', system-ui, sans-serif";
const ONEST = "'Onest', -apple-system, 'Segoe UI', system-ui, sans-serif";
const PLAYFAIR = "'Playfair Display', Georgia, 'Times New Roman', serif";
const MONO = "'IBM Plex Mono', 'SF Mono', Menlo, monospace";

export const tokenSets: DesignTokens[] = [
  {
    // 0 · Ink & Lime — the flagship tech look: graphite room lit by an acid-lime accent.
    "--color-bg": "#0C0D0F",
    "--color-surface": "#16181C",
    "--color-text": "#F2F4F6",
    "--color-text-muted": "#8C939C",
    "--color-primary": "#C8F751",
    "--color-primary-contrast": "#0C0D0F",
    "--color-accent": "#5EE6C5",
    "--color-border": "#24272D",
    "--color-sale": "#FF5C5C",
    "--color-ink": "#F2F4F6",
    "--color-ink-text": "#0C0D0F",
    "--color-ink-primary": "#3F7A12",
    "--color-ink-primary-contrast": "#FFFFFF",
    "--font-heading": UNBOUNDED,
    "--font-body": GOLOS,
    "--font-numeric": MONO,
    "--radius-sm": "4px",
    "--radius-md": "8px",
    "--radius-lg": "14px",
    "--shadow-card": "0 1px 2px rgba(0,0,0,0.5), 0 18px 44px rgba(0,0,0,0.45)",
    "--shadow-elevated": "0 32px 70px rgba(0,0,0,0.6)",
  },
  {
    // 1 · Midnight Violet — the same dark architecture, but electric violet and cooler blacks.
    "--color-bg": "#0B0A14",
    "--color-surface": "#151327",
    "--color-text": "#EFECFF",
    "--color-text-muted": "#8E88AD",
    "--color-primary": "#8B5CF6",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#48D8FF",
    "--color-border": "#241F3D",
    "--color-sale": "#FF6B9D",
    "--color-ink": "#EFECFF",
    "--color-ink-text": "#12102A",
    "--color-ink-primary": "#5B21B6",
    "--color-ink-primary-contrast": "#FFFFFF",
    "--font-heading": UNBOUNDED,
    "--font-body": MANROPE,
    "--font-numeric": MONO,
    "--radius-sm": "4px",
    "--radius-md": "10px",
    "--radius-lg": "18px",
    "--shadow-card": "0 1px 2px rgba(0,0,0,0.5), 0 20px 50px rgba(20,10,60,0.5)",
    "--shadow-elevated": "0 34px 80px rgba(20,10,60,0.65)",
  },
  {
    // 2 · Linen Studio — bone paper, clay accents, Playfair headlines. Textiles and homeware.
    "--color-bg": "#FBF8F3",
    "--color-surface": "#F2ECE2",
    "--color-text": "#241E18",
    "--color-text-muted": "#867B6C",
    "--color-primary": "#A8613F",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#C9A87C",
    "--color-border": "#E6DDCE",
    "--color-sale": "#C0442F",
    "--color-ink": "#241E18",
    "--color-ink-text": "#FBF8F3",
    "--color-ink-primary": "#D9B27C",
    "--color-ink-primary-contrast": "#241E18",
    "--font-heading": PLAYFAIR,
    "--font-body": MANROPE,
    "--font-numeric": MANROPE,
    "--radius-sm": "3px",
    "--radius-md": "6px",
    "--radius-lg": "12px",
    "--shadow-card": "0 1px 2px rgba(36,30,24,0.04), 0 14px 36px rgba(36,30,24,0.07)",
    "--shadow-elevated": "0 28px 64px rgba(36,30,24,0.14)",
  },
  {
    // 3 · Sage Market — cool herbal green on oat. Eco/organic goods, tea, candles.
    "--color-bg": "#F7F8F4",
    "--color-surface": "#EDF0E7",
    "--color-text": "#1F2A22",
    "--color-text-muted": "#748073",
    "--color-primary": "#4A7C59",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#B7C9A8",
    "--color-border": "#DDE3D4",
    "--color-sale": "#C25A38",
    "--color-ink": "#1F2A22",
    "--color-ink-text": "#F7F8F4",
    "--color-ink-primary": "#B7C9A8",
    "--color-ink-primary-contrast": "#1F2A22",
    "--font-heading": ONEST,
    "--font-body": ONEST,
    "--font-numeric": ONEST,
    "--radius-sm": "5px",
    "--radius-md": "10px",
    "--radius-lg": "18px",
    "--shadow-card": "0 1px 2px rgba(31,42,34,0.04), 0 12px 32px rgba(31,42,34,0.07)",
    "--shadow-elevated": "0 26px 60px rgba(31,42,34,0.13)",
  },
  {
    // 4 · Cocoa Cream — roasted brown on cream, serif headlines. Coffee, chocolate, leather.
    "--color-bg": "#FAF6F0",
    "--color-surface": "#F0E7DA",
    "--color-text": "#2A1F17",
    "--color-text-muted": "#8B7A67",
    "--color-primary": "#7A4E2D",
    "--color-primary-contrast": "#FFF8F0",
    "--color-accent": "#D9A566",
    "--color-border": "#E7DACA",
    "--color-sale": "#B4482D",
    "--color-ink": "#2A1F17",
    "--color-ink-text": "#FAF6F0",
    "--color-ink-primary": "#D9A566",
    "--color-ink-primary-contrast": "#2A1F17",
    "--font-heading": PLAYFAIR,
    "--font-body": GOLOS,
    "--font-numeric": GOLOS,
    "--radius-sm": "3px",
    "--radius-md": "7px",
    "--radius-lg": "14px",
    "--shadow-card": "0 1px 2px rgba(42,31,23,0.05), 0 14px 34px rgba(42,31,23,0.08)",
    "--shadow-elevated": "0 28px 62px rgba(42,31,23,0.15)",
  },
  {
    // 5 · Berry Pop — the flagship pop look: milky pink room, hot berry accent, pill geometry.
    "--color-bg": "#FFF6F7",
    "--color-surface": "#FFEAEF",
    "--color-text": "#2B0E1B",
    "--color-text-muted": "#96707E",
    "--color-primary": "#E0326E",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#FFB44D",
    "--color-border": "#FBD8E1",
    "--color-sale": "#D81E5B",
    "--color-ink": "#2B0E1B",
    "--color-ink-text": "#FFF6F7",
    "--color-ink-primary": "#FF7BA8",
    "--color-ink-primary-contrast": "#2B0E1B",
    "--font-heading": UNBOUNDED,
    "--font-body": ONEST,
    "--font-numeric": ONEST,
    "--radius-sm": "8px",
    "--radius-md": "16px",
    "--radius-lg": "28px",
    "--shadow-card": "0 1px 2px rgba(126,20,60,0.05), 0 14px 36px rgba(126,20,60,0.10)",
    "--shadow-elevated": "0 28px 64px rgba(126,20,60,0.18)",
  },
  {
    // 6 · Sunburst — cream + tangerine, maximum energy. Sport, kids, snacks.
    "--color-bg": "#FFFBF2",
    "--color-surface": "#FFF1D9",
    "--color-text": "#231703",
    "--color-text-muted": "#8B7550",
    "--color-primary": "#F26419",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#2EC4B6",
    "--color-border": "#F6E3C4",
    "--color-sale": "#E01E37",
    "--color-ink": "#231703",
    "--color-ink-text": "#FFFBF2",
    "--color-ink-primary": "#FFB000",
    "--color-ink-primary-contrast": "#231703",
    "--font-heading": UNBOUNDED,
    "--font-body": MANROPE,
    "--font-numeric": MANROPE,
    "--radius-sm": "8px",
    "--radius-md": "16px",
    "--radius-lg": "26px",
    "--shadow-card": "0 1px 2px rgba(60,35,0,0.05), 0 14px 34px rgba(60,35,0,0.10)",
    "--shadow-elevated": "0 28px 62px rgba(60,35,0,0.17)",
  },
  {
    // 7 · Arctic Blue — clean marketplace blue on paper white. The safe, universal storefront.
    "--color-bg": "#F8FAFC",
    "--color-surface": "#EEF3F9",
    "--color-text": "#0F1B2A",
    "--color-text-muted": "#6B7B8E",
    "--color-primary": "#1D6FEB",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#00C2A8",
    "--color-border": "#DCE5EF",
    "--color-sale": "#E8324C",
    "--color-ink": "#0F1B2A",
    "--color-ink-text": "#F8FAFC",
    "--color-ink-primary": "#63A4FF",
    "--color-ink-primary-contrast": "#0F1B2A",
    "--font-heading": ONEST,
    "--font-body": GOLOS,
    "--font-numeric": GOLOS,
    "--radius-sm": "6px",
    "--radius-md": "12px",
    "--radius-lg": "20px",
    "--shadow-card": "0 1px 2px rgba(15,27,42,0.05), 0 12px 30px rgba(15,27,42,0.08)",
    "--shadow-elevated": "0 26px 58px rgba(15,27,42,0.14)",
  },
  {
    // 8 · Graphite — near-monochrome light: black CTA, paper grey, no color noise at all.
    "--color-bg": "#FAFAFA",
    "--color-surface": "#F0F0F0",
    "--color-text": "#111111",
    "--color-text-muted": "#767676",
    "--color-primary": "#141414",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#B49660",
    "--color-border": "#E2E2E2",
    "--color-sale": "#D02B2B",
    "--color-ink": "#111111",
    "--color-ink-text": "#FAFAFA",
    "--color-ink-primary": "#C9AE78",
    "--color-ink-primary-contrast": "#111111",
    "--font-heading": ONEST,
    "--font-body": MANROPE,
    "--font-numeric": MONO,
    "--radius-sm": "2px",
    "--radius-md": "4px",
    "--radius-lg": "8px",
    "--shadow-card": "0 1px 2px rgba(0,0,0,0.04), 0 12px 30px rgba(0,0,0,0.07)",
    "--shadow-elevated": "0 26px 58px rgba(0,0,0,0.13)",
  },
];
