import type { DesignTokens } from "@sitegen/shared-ui/types.ts";

const SANS = "-apple-system, 'Segoe UI', system-ui, sans-serif";

export const tokenSets: DesignTokens[] = [
  {
    // Clinical Blue
    "--color-bg": "#F5FAFC",
    "--color-surface": "#E8F3F7",
    "--color-text": "#132227",
    "--color-text-muted": "#546A72",
    "--color-primary": "#0F7A8C",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#4FC1D6",
    "--color-border": "#D6E8ED",
    "--font-heading": SANS,
    "--font-body": SANS,
    "--radius-sm": "8px",
    "--radius-md": "14px",
    "--radius-lg": "22px",
    "--shadow-card": "0 4px 14px rgba(19,34,39,0.08)",
    "--shadow-elevated": "0 12px 30px rgba(19,34,39,0.14)",
  },
  {
    // Soft Mint
    "--color-bg": "#F6FBF8",
    "--color-surface": "#E6F5EC",
    "--color-text": "#122A1D",
    "--color-text-muted": "#4E6B58",
    "--color-primary": "#2E9E6B",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#7BD9AC",
    "--color-border": "#D6EEDF",
    "--font-heading": SANS,
    "--font-body": SANS,
    "--radius-sm": "8px",
    "--radius-md": "16px",
    "--radius-lg": "24px",
    "--shadow-card": "0 4px 14px rgba(18,42,29,0.08)",
    "--shadow-elevated": "0 12px 30px rgba(18,42,29,0.14)",
  },
  {
    // Pure Clinic
    "--color-bg": "#FFFFFF",
    "--color-surface": "#F2F4F6",
    "--color-text": "#14181C",
    "--color-text-muted": "#5C6570",
    "--color-primary": "#2563AC",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#2563AC",
    "--color-border": "#E4E8EC",
    "--font-heading": SANS,
    "--font-body": SANS,
    "--radius-sm": "4px",
    "--radius-md": "8px",
    "--radius-lg": "12px",
    "--shadow-card": "0 2px 10px rgba(20,24,28,0.06)",
    "--shadow-elevated": "0 10px 26px rgba(20,24,28,0.1)",
  },
  {
    // Warm Care
    "--color-bg": "#FFFAF6",
    "--color-surface": "#FBEEE2",
    "--color-text": "#2B2016",
    "--color-text-muted": "#7A6A57",
    "--color-primary": "#D97757",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#D97757",
    "--color-border": "#F0DFCE",
    "--font-heading": SANS,
    "--font-body": SANS,
    "--radius-sm": "10px",
    "--radius-md": "16px",
    "--radius-lg": "26px",
    "--shadow-card": "0 4px 16px rgba(43,32,22,0.10)",
    "--shadow-elevated": "0 12px 30px rgba(43,32,22,0.16)",
  },
  {
    // Night Clinic
    "--color-bg": "#101820",
    "--color-surface": "#182430",
    "--color-text": "#E8F1F5",
    "--color-text-muted": "#8CA0AC",
    "--color-primary": "#4FC1D6",
    "--color-primary-contrast": "#101820",
    "--color-accent": "#4FC1D6",
    "--color-border": "#233240",
    "--font-heading": SANS,
    "--font-body": SANS,
    "--radius-sm": "6px",
    "--radius-md": "12px",
    "--radius-lg": "20px",
    "--shadow-card": "0 4px 18px rgba(0,0,0,0.4)",
    "--shadow-elevated": "0 14px 34px rgba(0,0,0,0.5)",
  },
];
