import { defineConfig } from "astro/config";

// Bespoke site (not generated by cli/new-site). Lives on GitHub Pages under the repo prefix.
export default defineConfig({
  site: "https://kpopsdeath14.github.io",
  base: "/small-business-sites/simracing-shop",
});
