import type { DesignTokens } from "@sitegen/shared-ui/types.ts";

const SERIF = "Georgia, 'Times New Roman', serif";
const SANS = "-apple-system, 'Segoe UI', system-ui, sans-serif";
const ROUNDED = "'Century Gothic', -apple-system, system-ui, sans-serif";

export const tokenSets: DesignTokens[] = [
  {
    // Trattoria Warm
    "--color-bg": "#FBF6EE",
    "--color-surface": "#F3E9D8",
    "--color-text": "#2B2118",
    "--color-text-muted": "#6B5E4F",
    "--color-primary": "#C1440E",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#D99B2B",
    "--color-border": "#E4D8C4",
    "--font-heading": SERIF,
    "--font-body": SANS,
    "--radius-sm": "6px",
    "--radius-md": "12px",
    "--radius-lg": "20px",
    "--shadow-card": "0 4px 16px rgba(43,33,24,0.10)",
    "--shadow-elevated": "0 12px 32px rgba(43,33,24,0.16)",
  },
  {
    // Modern Bistro
    "--color-bg": "#F7F7F2",
    "--color-surface": "#EDEEE6",
    "--color-text": "#1F241F",
    "--color-text-muted": "#5B655B",
    "--color-primary": "#2F5233",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#8A9A5B",
    "--color-border": "#DADDD2",
    "--font-heading": SANS,
    "--font-body": SANS,
    "--radius-sm": "3px",
    "--radius-md": "6px",
    "--radius-lg": "10px",
    "--shadow-card": "0 2px 10px rgba(31,36,31,0.08)",
    "--shadow-elevated": "0 8px 24px rgba(31,36,31,0.14)",
  },
  {
    // Noir Fine Dining
    "--color-bg": "#141414",
    "--color-surface": "#1F1F1F",
    "--color-text": "#EDEAE3",
    "--color-text-muted": "#A6A199",
    "--color-primary": "#C9A227",
    "--color-primary-contrast": "#141414",
    "--color-accent": "#C9A227",
    "--color-border": "#333333",
    "--font-heading": SERIF,
    "--font-body": SANS,
    "--radius-sm": "0px",
    "--radius-md": "2px",
    "--radius-lg": "4px",
    "--shadow-card": "0 4px 20px rgba(0,0,0,0.5)",
    "--shadow-elevated": "0 16px 40px rgba(0,0,0,0.6)",
  },
  {
    // Sunny Cafe
    "--color-bg": "#FFFDF7",
    "--color-surface": "#FFF3DC",
    "--color-text": "#3A2B14",
    "--color-text-muted": "#8A7355",
    "--color-primary": "#E8871E",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#E8871E",
    "--color-border": "#F0DFB8",
    "--font-heading": ROUNDED,
    "--font-body": SANS,
    "--radius-sm": "10px",
    "--radius-md": "16px",
    "--radius-lg": "28px",
    "--shadow-card": "0 6px 18px rgba(232,135,30,0.15)",
    "--shadow-elevated": "0 14px 36px rgba(232,135,30,0.22)",
  },
  {
    // Coastal Fresh
    "--color-bg": "#F4FAF9",
    "--color-surface": "#E4F1EF",
    "--color-text": "#0F2B28",
    "--color-text-muted": "#54706C",
    "--color-primary": "#1B7A72",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#3FA7C9",
    "--color-border": "#D3E7E4",
    "--font-heading": SANS,
    "--font-body": SANS,
    "--radius-sm": "6px",
    "--radius-md": "10px",
    "--radius-lg": "16px",
    "--shadow-card": "0 4px 14px rgba(15,43,40,0.10)",
    "--shadow-elevated": "0 12px 30px rgba(15,43,40,0.16)",
  },
];
