import type { DesignTokens } from "@sitegen/shared-ui/types.ts";

const SANS = "-apple-system, 'Segoe UI', system-ui, sans-serif";
const CONDENSED = "'Arial Narrow', -apple-system, system-ui, sans-serif";

export const tokenSets: DesignTokens[] = [
  {
    // Road Blue
    "--color-bg": "#F5F8FC",
    "--color-surface": "#E8EFF9",
    "--color-text": "#101826",
    "--color-text-muted": "#54607A",
    "--color-primary": "#1E5AA8",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#F2A900",
    "--color-border": "#D7E1F0",
    "--font-heading": SANS,
    "--font-body": SANS,
    "--radius-sm": "4px",
    "--radius-md": "8px",
    "--radius-lg": "14px",
    "--shadow-card": "0 4px 14px rgba(16,24,38,0.10)",
    "--shadow-elevated": "0 12px 30px rgba(16,24,38,0.16)",
  },
  {
    // Safety Yellow
    "--color-bg": "#FFFDF5",
    "--color-surface": "#FFF3CE",
    "--color-text": "#1A1A1A",
    "--color-text-muted": "#5C5646",
    "--color-primary": "#101826",
    "--color-primary-contrast": "#F2A900",
    "--color-accent": "#F2A900",
    "--color-border": "#F0E1A8",
    "--font-heading": CONDENSED,
    "--font-body": SANS,
    "--radius-sm": "2px",
    "--radius-md": "4px",
    "--radius-lg": "8px",
    "--shadow-card": "0 4px 14px rgba(0,0,0,0.10)",
    "--shadow-elevated": "0 12px 28px rgba(0,0,0,0.18)",
  },
  {
    // Night Drive
    "--color-bg": "#0F1620",
    "--color-surface": "#182333",
    "--color-text": "#EAF1FB",
    "--color-text-muted": "#8FA0BC",
    "--color-primary": "#33C7E8",
    "--color-primary-contrast": "#0F1620",
    "--color-accent": "#33C7E8",
    "--color-border": "#26344A",
    "--font-heading": SANS,
    "--font-body": SANS,
    "--radius-sm": "6px",
    "--radius-md": "10px",
    "--radius-lg": "18px",
    "--shadow-card": "0 4px 18px rgba(0,0,0,0.4)",
    "--shadow-elevated": "0 16px 36px rgba(0,0,0,0.5)",
  },
  {
    // Fresh Green
    "--color-bg": "#F6FAF6",
    "--color-surface": "#E7F3E7",
    "--color-text": "#16241A",
    "--color-text-muted": "#546B58",
    "--color-primary": "#2E8B4F",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#8BC34A",
    "--color-border": "#D6E8D8",
    "--font-heading": SANS,
    "--font-body": SANS,
    "--radius-sm": "8px",
    "--radius-md": "14px",
    "--radius-lg": "22px",
    "--shadow-card": "0 4px 14px rgba(22,36,26,0.10)",
    "--shadow-elevated": "0 12px 30px rgba(22,36,26,0.16)",
  },
  {
    // Classic Red
    "--color-bg": "#FFFFFF",
    "--color-surface": "#FBECEC",
    "--color-text": "#1C1C1C",
    "--color-text-muted": "#6B5E5E",
    "--color-primary": "#D32F2F",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#D32F2F",
    "--color-border": "#EFD9D9",
    "--font-heading": CONDENSED,
    "--font-body": SANS,
    "--radius-sm": "2px",
    "--radius-md": "4px",
    "--radius-lg": "6px",
    "--shadow-card": "0 2px 10px rgba(0,0,0,0.08)",
    "--shadow-elevated": "0 10px 26px rgba(0,0,0,0.14)",
  },
];
