import type { DesignTokens } from "@sitegen/shared-ui/types.ts";

const SANS = "-apple-system, 'Segoe UI', system-ui, sans-serif";
const SERIF_BOLD = "Georgia, 'Times New Roman', serif";

export const tokenSets: DesignTokens[] = [
  {
    // Classic Barber
    "--color-bg": "#141312",
    "--color-surface": "#1F1D1B",
    "--color-text": "#EFEAE3",
    "--color-text-muted": "#A69C90",
    "--color-primary": "#B3282D",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#B3282D",
    "--color-border": "#332F2B",
    "--font-heading": SERIF_BOLD,
    "--font-body": SANS,
    "--radius-sm": "2px",
    "--radius-md": "4px",
    "--radius-lg": "8px",
    "--shadow-card": "0 4px 18px rgba(0,0,0,0.45)",
    "--shadow-elevated": "0 14px 34px rgba(0,0,0,0.55)",
  },
  {
    // Leather & Wood
    "--color-bg": "#F4EEE6",
    "--color-surface": "#E7DBC8",
    "--color-text": "#2E2013",
    "--color-text-muted": "#77644C",
    "--color-primary": "#6B3E26",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#B08C4F",
    "--color-border": "#DDCBAE",
    "--font-heading": SERIF_BOLD,
    "--font-body": SANS,
    "--radius-sm": "4px",
    "--radius-md": "8px",
    "--radius-lg": "14px",
    "--shadow-card": "0 4px 14px rgba(46,32,19,0.14)",
    "--shadow-elevated": "0 12px 30px rgba(46,32,19,0.2)",
  },
  {
    // Modern Urban
    "--color-bg": "#FAFAFA",
    "--color-surface": "#EFEFEF",
    "--color-text": "#161616",
    "--color-text-muted": "#666666",
    "--color-primary": "#161616",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#161616",
    "--color-border": "#E0E0E0",
    "--font-heading": SANS,
    "--font-body": SANS,
    "--radius-sm": "0px",
    "--radius-md": "2px",
    "--radius-lg": "4px",
    "--shadow-card": "0 2px 8px rgba(0,0,0,0.06)",
    "--shadow-elevated": "0 10px 24px rgba(0,0,0,0.1)",
  },
  {
    // Barber Pole
    "--color-bg": "#FFFFFF",
    "--color-surface": "#EEF3F8",
    "--color-text": "#0F1C2E",
    "--color-text-muted": "#5A6B80",
    "--color-primary": "#1B3A66",
    "--color-primary-contrast": "#FFFFFF",
    "--color-accent": "#C8272C",
    "--color-border": "#DCE5EE",
    "--font-heading": SANS,
    "--font-body": SANS,
    "--radius-sm": "4px",
    "--radius-md": "8px",
    "--radius-lg": "14px",
    "--shadow-card": "0 4px 14px rgba(15,28,46,0.10)",
    "--shadow-elevated": "0 12px 28px rgba(15,28,46,0.16)",
  },
  {
    // Industrial Dark
    "--color-bg": "#1B1B1D",
    "--color-surface": "#242427",
    "--color-text": "#EDEDEE",
    "--color-text-muted": "#9C9C9F",
    "--color-primary": "#C97A3D",
    "--color-primary-contrast": "#1B1B1D",
    "--color-accent": "#C97A3D",
    "--color-border": "#37373B",
    "--font-heading": SANS,
    "--font-body": SANS,
    "--radius-sm": "2px",
    "--radius-md": "6px",
    "--radius-lg": "10px",
    "--shadow-card": "0 4px 18px rgba(0,0,0,0.4)",
    "--shadow-elevated": "0 14px 34px rgba(0,0,0,0.5)",
  },
];
